//array of possible button colros
var buttonColors = ["red", "blue", "green", "yellow"];


//array with all colors generated by the game
var gamePattern = [];
//array with colors the user has clicked
var userClickedPattern = [];

var started = false;

var level = 0;
//starting game  with  kepress
$(document).keypress(function() {
  if (!started) {
    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});

//storing the color that the user clicks
$(".btn").click(function(){
  var userChosenColor = $(this).attr("id");
  userClickedPattern.push(userChosenColor);
  playSound(userChosenColor);
  animatePress(userChosenColor);
  checkAnswer(userClickedPattern.length-1);
});


function nextSequence() {
  //Reset user click pattern to zero
  userClickedPattern = [];

  level++;
  $("#level-title").text("Level " + level);

//creating random number
  var randomNumber = Math.floor(Math.random()*4);
//assigning random number to color
  var randomChosenColor = buttonColors[randomNumber];
//pushing color to pattern array
  gamePattern.push(randomChosenColor);
//blinking random color
  $("#" + randomChosenColor).fadeOut(250).fadeIn(250);
//playing color noise
  playSound(randomChosenColor);
//  var audio = new Audio("sounds/" + randomChosenColor + ".mp3");
//audio.play();
}

//checking user answer against the game sequence
function checkAnswer(currentLevel) {
  if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
    console.log("Success");

    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(function() {
        nextSequence();
      }, 1000);
      }
  } else {
      console.log("wrong");
      wrongSound();
      $("body").addClass("game-over");

      setTimeout(function() {
        $("body").removeClass("game-over");
      }, 200);

      $("h1").text("Game Over, Press Any Key to Restart");

      startOver();

    }
  }




//play sound function - refactored into other uses
function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}
//wrong answer sound
function wrongSound(name) {
  var wrongSound = new Audio("sounds/wrong.mp3");
  wrongSound.play();
}
//changes background to grey during press
function animatePress(currentColor) {
  $("#" + currentColor ).addClass("pressed");

  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}

//Start Over function
function startOver(){
  level = [];
  gamePattern = [];
  started = false;
}
